#!/bin/bash

KTEST_FILE_DIR=$1

OUTPUT_TMP_DIR=klee-output-tmp


ROOT_DIR=${PWD}/../
SCRIPT_DIR=${ROOT_DIR}/klee_scripts
BUILD_DIR=${ROOT_DIR}/build
# SMT2_FILENAME=${BUILD_DIR}/tmp/${OUTPUT_TMP_ID}-constraints.smt2

Z3_OUTPUT_FILENAME=${BUILD_DIR}/${OUTPUT_FILENAME}

# set -o xtrace

# call klee to generate smt2 constraints 
# mkdir -p ${OUTPUT_TMP_DIR}

# gen_constraint (pid.constraint) 

# ${SCRIPT_DIR}/run_klee.sh ${BUILD_DIR}/whole.bc ops ${BUILD_DIR}/${KTEST_FILENAME} > /dev/null 2>&1

KLEE_PATH=/home/klee/klee_src/build/bin/

${KLEE_PATH}/klee \
    --write-smt2s \
    --warnings-only-to-file --output-stats=0 \
    --entry-point=ops_wrapper \
    --posix-runtime --libc=uclibc \
    --use-forked-solver=0 \
    --seed-dir=${KTEST_FILE_DIR} \
    --named-seed-matching --only-replay-seeds \
    --always-output-seeds=0 --use-branch-cache=0 \
    --output-dir=${OUTPUT_TMP_DIR} \
    ${BUILD_DIR}/whole.bc 



    # --seed-file=${BUILD_DIR}/0-gen.ktest \
    # --seed-file=${BUILD_DIR}/1-gen.ktest \

# mv ${OUTPUT_TMP_DIR}/test000001.smt2 ${SMT2_FILENAME}
# mv ${OUTPUT_TMP_DIR}/test000001.smt2 ${SMT2_FILENAME}
# mv klee-last/test000001.ktest ${BUILD_DIR}/basic.ktest # equivalent output file generated by klee
# mv klee-last/test000001.smt2 $SMT2_FILENAME

# rm -rf ${OUTPUT_TMP_DIR}

# solve smt constraints
# ITERS=1
# ${SCRIPT_DIR}/run_z3.py ${SMT2_FILENAME} ${ITERS} >> ${OUTPUT_FILENAME}

